language: node_js
node_js:
  - "5"
env:
  - CXX=g++-4.8 TRAVIS=true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: mocha --timeout 60s
before_script:
  - npm install -g ethereumjs-testrpc@3.0.0
  - npm install
  - chmod +x rpc.sh
  - ./rpc.sh > /dev/null & 
  - sleep 3
