language: node_js
node_js:
  - "5"
env:
  - CXX=g++-4.8 TRAVIS=true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: truffle test
before_script:
  - npm install -g ethereumjs-testrpc
  - npm install
  - testrpc > /dev/null & 
