language: node_js
node_js:
    - v5
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - sh -e /etc/init.d/xvfb start
script: gulp test
before_script:
    - npm install

